// LTC from an audio input (phase 5a, 時間碼模式): getUserMedia with every voice processing off (echo
// cancellation, noise suppression and auto gain would destroy the square wave), the app's shared
// AudioContext, and the static AudioWorklet public/worklets/ltc-decoder.js (the LtcDecoder of
// ltc.ts, generated by scripts/build-worklets.mjs) on the first two channels. Decoded frames come
// back with their sample positions; ContextClock turns those into the console's clock (Date.now()
// ms) without the main thread's message delays, and each frame's position gets its one frame of
// decode latency back. Browser only (ContextClock is pure).

import { getSharedAudioContext } from "@/lib/audio/live";
import type { LtcFrame } from "./ltc";
import type { LtcWorkletMessage } from "./ltc-worklet";
import { frameSeconds, tcToSeconds, type FrameRate, type Timecode } from "./timecode";

export const LTC_WORKLET_URL = "/worklets/ltc-decoder.js";
export const LTC_PROCESSOR = "livelyrics-ltc";

export interface LtcInputFrame {
  /** real seconds since 00:00:00:00 at `at` (the decode latency added back) */
  position: number;
  /** Date.now() ms */
  at: number;
  rate: FrameRate;
  direction: 1 | -1;
  label: Timecode;
  channel: number;
}

/**
 * Maps AudioContext sample positions to Date.now(): every message says which sample the audio
 * thread had reached when it was posted; the least-delayed message of the last seconds fixes the
 * offset (a busy main thread only ever delays messages, never hurries them).
 */
export class ContextClock {
  private samples: Array<{ at: number; offset: number }> = [];

  constructor(
    private readonly windowMs = 5000,
    /** capture latency (ms) to take off: the sample was heard this long before the worklet saw it */
    private latencyMs = 10,
  ) {}

  setLatency(ms: number): void {
    if (Number.isFinite(ms) && ms >= 0 && ms < 500) this.latencyMs = ms;
  }

  observe(frame: number, sampleRate: number, receivedAt: number): void {
    const offset = receivedAt - (frame / sampleRate) * 1000;
    this.samples.push({ at: receivedAt, offset });
    while (this.samples.length > 1 && receivedAt - this.samples[0].at > this.windowMs) this.samples.shift();
  }

  /** Date.now() ms of context sample `frame`, or null before any message. */
  timeOf(frame: number, sampleRate: number): number | null {
    if (!this.samples.length) return null;
    let min = Number.POSITIVE_INFINITY;
    for (const s of this.samples) if (s.offset < min) min = s.offset;
    return (frame / sampleRate) * 1000 + min - this.latencyMs;
  }
}

/** A decoded frame → a chase position: the tape is one frame past the label when the frame ends. */
export function framePosition(f: Pick<LtcFrame, "hours" | "minutes" | "seconds" | "frames" | "dropFrame" | "fps" | "reverse">): { position: number; rate: FrameRate; label: Timecode } {
  const rate: FrameRate = f.dropFrame ? 29.97 : f.fps;
  const label = { hours: f.hours, minutes: f.minutes, seconds: f.seconds, frames: f.frames };
  // backwards the sync word of the frame before arrives 0.2 frames after this frame's data
  const lead = f.reverse ? -0.2 : 1;
  return { position: tcToSeconds(label, rate) + lead * frameSeconds(rate), rate, label };
}

export class LtcInputError extends Error {
  constructor(
    message: string,
    readonly code: "unsupported" | "insecure" | "denied" | "not-found" | "busy" | "failed",
    options?: { cause?: unknown },
  ) {
    super(message, options);
    this.name = "LtcInputError";
  }
}

function inputError(err: unknown): LtcInputError {
  const name = typeof err === "object" && err !== null ? String((err as { name?: unknown }).name ?? "") : "";
  switch (name) {
    case "NotAllowedError":
    case "PermissionDeniedError":
    case "SecurityError":
      return new LtcInputError("音訊輸入權限被拒絕。請在網址列左側的網站設定允許使用麥克風（音訊輸入）後再試一次。", "denied", { cause: err });
    case "NotFoundError":
    case "DevicesNotFoundError":
    case "OverconstrainedError":
    case "ConstraintNotSatisfiedError":
      return new LtcInputError("找不到這個音訊輸入裝置，請確認錄音介面已連接，或重新選擇輸入。", "not-found", { cause: err });
    case "NotReadableError":
    case "TrackStartError":
      return new LtcInputError("音訊輸入裝置無法開啟，可能正被其他程式使用。", "busy", { cause: err });
    default: {
      const detail = err instanceof Error && err.message ? `（${err.message}）` : "";
      return new LtcInputError(`無法開啟 LTC 音訊輸入${detail}。`, "failed", { cause: err });
    }
  }
}

const loaded = new WeakMap<BaseAudioContext, Promise<void>>();

function loadWorklet(ctx: AudioContext): Promise<void> {
  let p = loaded.get(ctx);
  if (!p) {
    p = ctx.audioWorklet.addModule(LTC_WORKLET_URL);
    loaded.set(ctx, p);
    p.catch(() => loaded.delete(ctx));
  }
  return p;
}

export interface LtcInputHandlers {
  onFrame(frame: LtcInputFrame): void;
  /** input peak 0..1, ten times a second */
  onLevel(peak: number): void;
  /** the device went away */
  onEnded(message: string): void;
}

/** One running LTC input. */
export class LtcInput {
  private readonly clock = new ContextClock();
  private disposed = false;
  private activeChannel: number | null = null;

  private constructor(
    private readonly ctx: AudioContext,
    private readonly stream: MediaStream,
    private readonly source: MediaStreamAudioSourceNode,
    private readonly node: AudioWorkletNode,
    private readonly handlers: LtcInputHandlers,
  ) {
    const track = stream.getAudioTracks()[0];
    const latency = (track?.getSettings?.() as MediaTrackSettings & { latency?: number } | undefined)?.latency;
    if (typeof latency === "number") this.clock.setLatency(latency * 1000);
    node.port.onmessage = (e: MessageEvent<LtcWorkletMessage>) => this.receive(e.data);
    if (track) track.onended = () => this.handlers.onEnded("LTC 的音訊輸入裝置已中斷連線。");
  }

  /** Open `deviceId` ("" = the default input) and start decoding. Call from a user gesture when possible. */
  static async start(deviceId: string, handlers: LtcInputHandlers): Promise<LtcInput> {
    if (typeof window !== "undefined" && window.isSecureContext === false) {
      throw new LtcInputError("瀏覽器只允許在 localhost 或 HTTPS 下使用音訊輸入，請改用 http://localhost 開啟。", "insecure");
    }
    const media = typeof navigator !== "undefined" ? navigator.mediaDevices : undefined;
    if (!media || typeof media.getUserMedia !== "function") throw new LtcInputError("這個瀏覽器不支援音訊輸入，無法接收 LTC。", "unsupported");
    const ctx = getSharedAudioContext();
    if (!ctx || !ctx.audioWorklet || typeof AudioWorkletNode === "undefined") throw new LtcInputError("這個瀏覽器不支援 AudioWorklet，無法解碼 LTC。請改用最新版的 Chrome、Edge 或 Safari。", "unsupported");
    // resume inside the caller's gesture, before the permission prompt consumes it
    const resumed = ctx.state === "running" ? Promise.resolve() : ctx.resume().catch(() => {});
    let stream: MediaStream;
    try {
      stream = await media.getUserMedia({
        audio: {
          ...(deviceId ? { deviceId: { exact: deviceId } } : {}),
          echoCancellation: false,
          noiseSuppression: false,
          autoGainControl: false,
          channelCount: { ideal: 2 },
        },
        video: false,
      });
    } catch (err) {
      throw inputError(err);
    }
    try {
      await loadWorklet(ctx);
      await resumed;
      const source = ctx.createMediaStreamSource(stream);
      const node = new AudioWorkletNode(ctx, LTC_PROCESSOR, { numberOfInputs: 1, numberOfOutputs: 0, channelCount: 2, channelCountMode: "explicit", channelInterpretation: "discrete" });
      source.connect(node);
      return new LtcInput(ctx, stream, source, node, handlers);
    } catch (err) {
      for (const t of stream.getTracks()) t.stop();
      const detail = err instanceof Error && err.message ? `（${err.message}）` : "";
      throw new LtcInputError(`無法啟動 LTC 解碼${detail}。`, "failed", { cause: err });
    }
  }

  /** The audio engine waits for a click (autoplay policy): nothing is decoded meanwhile. */
  get suspended(): boolean {
    return this.ctx.state === "suspended";
  }

  /** The input channel the timecode comes from (0-based), once decoded. */
  get channel(): number | null {
    return this.activeChannel;
  }

  stop(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.node.port.onmessage = null;
    try {
      this.source.disconnect();
      this.node.disconnect();
    } catch {
      /* already disconnected */
    }
    for (const t of this.stream.getTracks()) {
      t.onended = null;
      t.stop();
    }
  }

  private receive(msg: LtcWorkletMessage): void {
    if (this.disposed || !msg) return;
    const now = Date.now();
    this.clock.observe(msg.frame, msg.sampleRate, now);
    if (msg.type === "level") {
      this.handlers.onLevel(msg.peak);
      return;
    }
    this.activeChannel = msg.channel;
    for (const f of msg.frames) {
      const at = this.clock.timeOf(f.end, msg.sampleRate) ?? now;
      const { position, rate, label } = framePosition(f);
      this.handlers.onFrame({ position, at, rate, direction: f.reverse ? -1 : 1, label, channel: msg.channel });
    }
  }
}
