// Genre -> visual grammar: how a stage designer's instincts differ between a post-rock crescendo, a
// punk chant and a city-pop groove. Each rule is explainable (`why`) and says what it changes:
// palette tendency, scene family, lyric treatment, transition energy and typography, plus the motifs
// and the live convention it suggests. Matched against MusicBrainz tags / genres and the genre words
// of a Wikipedia summary (src/lib/server/designer/genre.ts). Curated; 20 genres.

import type { FontId, LyricStyleId, SceneId } from "@/lib/types";
import type { Scheme } from "../palette";

export type LyricDensity = "sparse" | "normal" | "dense";
export type MotionEnergy = "soft" | "medium" | "punchy";

export interface GenreRule {
  id: string;
  /** 繁中 name */
  label: string;
  /** MusicBrainz tags / English genre names (matched case-, space- and hyphen-insensitively) */
  tags: string[];
  /** words in a Chinese summary that name the genre */
  zh: string[];
  palette: { hues: number[]; saturation: number; scheme: Scheme; light: "dark" | "mid" | "bright"; note: string };
  /** scene family, most typical first; `avoid` fights the genre */
  scenes: SceneId[];
  avoid: SceneId[];
  lyrics: { verse: LyricStyleId; chorus: LyricStyleId; density: LyricDensity; note: string };
  motion: MotionEnergy;
  typography: { cjkFont: FontId; latinFont: FontId; weight: number; letterSpacing: number; note: string };
  motifs: string[];
  /** how the genre is played live, for the cue notes */
  live: string;
  /** the rule in one sentence */
  why: string;
}

export const GENRE_RULES: readonly GenreRule[] = [
  {
    id: "post-rock",
    label: "後搖滾",
    tags: ["post-rock", "post rock", "instrumental rock"],
    zh: ["後搖滾", "後搖", "器樂搖滾"],
    palette: { hues: [215, 200, 35], saturation: 0.55, scheme: "analogous", light: "dark", note: "冷藍灰的大片暗部，只在爆發點留一道暖光" },
    scenes: ["nebula", "particles", "waves", "tunnel"],
    avoid: ["grid"],
    lyrics: { verse: "hidden", chorus: "line-fade", density: "sparse", note: "多半是器樂，歌詞只留最關鍵的一兩句，讓畫面長時間鋪陳" },
    motion: "soft",
    typography: { cjkFont: "noto-serif-tc", latinFont: "space-grotesk", weight: 700, letterSpacing: 0.12, note: "安靜的宋體加寬字距，像電影字卡" },
    motifs: ["長曝光的光軌", "漸強的光牆", "遠方的地平線"],
    live: "漸強（crescendo）很長：畫面跟著慢慢堆疊，爆發點前一拍才放到最亮；安靜段真的收暗。",
    why: "後搖靠長時間的漸強推進，畫面要有耐心：大片暗部、慢慢累積的光，最後一次才全開。",
  },
  {
    id: "shoegaze",
    label: "自賞",
    tags: ["shoegaze", "shoegazing", "nu gaze", "nugaze", "blackgaze"],
    zh: ["自賞", "瞪鞋", "盯鞋"],
    palette: { hues: [320, 280, 190], saturation: 0.7, scheme: "analogous", light: "mid", note: "粉紫與青的霧面疊色" },
    scenes: ["nebula", "bokeh", "rain", "particles"],
    avoid: ["grid", "shards"],
    lyrics: { verse: "subtitle", chorus: "line-fade", density: "sparse", note: "人聲埋在音牆裡，歌詞當成質地，不當成字幕" },
    motion: "soft",
    typography: { cjkFont: "noto-serif-tc", latinFont: "playfair-display", weight: 600, letterSpacing: 0.06, note: "細緻的襯線，像被霧化的字" },
    motifs: ["失焦的光暈", "音牆的霧"],
    live: "吉他音牆很厚：畫面用柔焦與霧，避免銳利的幾何與快切。",
    why: "自賞的聲音像一面霧牆，畫面要失焦、疊色、慢慢流動。",
  },
  {
    id: "dream-pop",
    label: "夢幻流行",
    tags: ["dream pop", "dreampop", "ethereal wave", "ethereal"],
    zh: ["夢幻流行", "夢幻泡泡"],
    palette: { hues: [300, 260, 180], saturation: 0.6, scheme: "analogous", light: "mid", note: "粉彩的紫、粉與淡青" },
    scenes: ["bokeh", "nebula", "particles", "gradient"],
    avoid: ["shards", "grid"],
    lyrics: { verse: "line-fade", chorus: "stack", density: "normal", note: "歌詞可以出現，但要柔、像詩一樣慢慢堆疊" },
    motion: "soft",
    typography: { cjkFont: "lxgw-wenkai-tc", latinFont: "playfair-display", weight: 700, letterSpacing: 0.08, note: "手寫楷書的溫柔" },
    motifs: ["漂浮的光斑", "粉彩的霧"],
    live: "旋律漂浮：轉場用光暈綻放，不要硬切。",
    why: "夢幻流行柔軟、懸浮：粉彩與光斑，節奏上不要硬切。",
  },
  {
    id: "city-pop",
    label: "城市流行",
    tags: ["city pop", "citypop", "aor", "yacht rock", "japanese city pop"],
    zh: ["城市流行", "都會流行"],
    palette: { hues: [320, 185, 40], saturation: 1, scheme: "complementary", light: "mid", note: "80 年代的夕陽粉、霓虹青與琥珀" },
    scenes: ["grid", "bokeh", "gradient", "waves"],
    avoid: ["ink", "blackout"],
    lyrics: { verse: "line-fade", chorus: "karaoke", density: "normal", note: "主歌上方淡入，副歌整行讓觀眾跟唱" },
    motion: "medium",
    typography: { cjkFont: "noto-sans-tc", latinFont: "bebas-neue", weight: 800, letterSpacing: 0.06, note: "復古招牌感的窄體大寫" },
    motifs: ["夕陽下的高速公路", "霓虹與棕櫚", "復古網格"],
    live: "律動輕快：畫面跟著拍子走，副歌讓觀眾跟唱。",
    why: "城市流行是 80 年代的夜景與夕陽：霓虹粉、青綠、復古網格。",
  },
  {
    id: "indie-rock",
    label: "獨立搖滾",
    tags: ["indie rock", "indie", "garage rock", "taiwanese indie", "chinese indie", "lo-fi indie"],
    zh: ["獨立搖滾", "獨立樂團", "獨立音樂"],
    palette: { hues: [210, 20], saturation: 0.75, scheme: "split", light: "mid", note: "像底片的低飽和原色" },
    scenes: ["ink", "shards", "particles", "rain"],
    avoid: [],
    lyrics: { verse: "line-fade", chorus: "karaoke", density: "normal", note: "觀眾會跟唱，副歌給大字；主歌退後" },
    motion: "medium",
    typography: { cjkFont: "noto-sans-tc", latinFont: "space-grotesk", weight: 800, letterSpacing: 0.04, note: "樸素、粗的黑體，不花俏" },
    motifs: ["底片顆粒", "手寫的字", "舊照片"],
    live: "畫面像樂團自己拍的 MV：粗糙、真實、不要太亮麗；大合唱時把歌詞放大。",
    why: "獨立搖滾的視覺像手工 zine 與底片：真實、有顆粒，不追求華麗。",
  },
  {
    id: "indie-pop",
    label: "獨立流行",
    tags: ["indie pop", "indiepop", "twee pop", "bedroom pop", "chamber pop", "jangle pop"],
    zh: ["獨立流行", "臥室流行"],
    palette: { hues: [40, 190, 340], saturation: 0.85, scheme: "triadic", light: "mid", note: "糖果色的黃、青與粉" },
    scenes: ["bokeh", "particles", "motif", "gradient"],
    avoid: ["ink"],
    lyrics: { verse: "line-fade", chorus: "word-pop", density: "normal", note: "歌詞可以俏皮地一個個跳出來" },
    motion: "medium",
    typography: { cjkFont: "huninn", latinFont: "space-grotesk", weight: 700, letterSpacing: 0.04, note: "圓體的友善與可愛" },
    motifs: ["手繪貼紙", "糖果色塊"],
    live: "輕快、可愛：跟著拍子讓字跳，但不要每句都跳。",
    why: "獨立流行輕盈、俏皮：糖果色與手繪感。",
  },
  {
    id: "folk",
    label: "民謠",
    tags: ["folk", "indie folk", "folk rock", "singer-songwriter", "singer/songwriter", "acoustic", "contemporary folk", "americana", "country", "folk pop"],
    zh: ["民謠", "民歌", "創作歌手", "創作型歌手"],
    palette: { hues: [30, 90, 20], saturation: 0.55, scheme: "analogous", light: "mid", note: "大地色：土、木、苔綠" },
    scenes: ["ink", "gradient", "bokeh", "motif"],
    avoid: ["grid", "tunnel"],
    lyrics: { verse: "stack", chorus: "line-fade", density: "normal", note: "歌詞是主角：讓字慢慢出現，詩句可以直排" },
    motion: "soft",
    typography: { cjkFont: "lxgw-wenkai-tc", latinFont: "playfair-display", weight: 700, letterSpacing: 0.06, note: "手寫楷書的溫度" },
    motifs: ["手寫的歌詞", "山與樹的剪影", "木頭與土地"],
    live: "安靜、有手感：不要閃爍，讓主唱與吉他說話。",
    why: "民謠說故事，字比特效重要：大地色、手寫字、留白。",
  },
  {
    id: "metal",
    label: "金屬",
    tags: ["metal", "heavy metal", "metalcore", "death metal", "black metal", "thrash metal", "doom metal", "nu metal", "progressive metal", "djent", "symphonic metal", "deathcore", "power metal", "sludge metal"],
    zh: ["金屬", "重金屬", "金屬核", "死亡金屬", "黑金屬", "鞭擊金屬"],
    palette: { hues: [0, 210], saturation: 0.8, scheme: "complementary", light: "dark", note: "黑、血紅與鋼鐵灰" },
    scenes: ["shards", "ink", "tunnel", "blackout"],
    avoid: ["bokeh", "gradient"],
    lyrics: { verse: "subtitle", chorus: "impact", density: "dense", note: "嘶吼聽不清楚：主歌小字幕或不放，大合唱段落給巨字" },
    motion: "punchy",
    typography: { cjkFont: "chiron-hei-hk", latinFont: "anton", weight: 900, letterSpacing: 0.02, note: "最粗、最重的字" },
    motifs: ["鏽蝕的鋼鐵", "裂開的符號", "黑色火焰"],
    live: "高強度、快切：跟著雙踏與斷奏切畫面（LED 安全模式會限制閃爍）；breakdown 可以全黑再炸開。",
    why: "金屬樂的畫面是重量與暗：黑、紅、鋼鐵，巨大的字與硬切。",
  },
  {
    id: "punk",
    label: "龐克",
    tags: ["punk", "punk rock", "pop punk", "hardcore punk", "hardcore", "skate punk", "street punk", "oi", "melodic hardcore"],
    zh: ["龐克", "朋克", "硬蕊", "流行龐克"],
    palette: { hues: [355, 55, 210], saturation: 1, scheme: "triadic", light: "mid", note: "影印海報的紅、黃、藍撞色" },
    scenes: ["shards", "grid", "motif", "particles"],
    avoid: ["bokeh", "nebula"],
    lyrics: { verse: "word-pop", chorus: "impact", density: "normal", note: "口號用巨字，全場一起喊" },
    motion: "punchy",
    typography: { cjkFont: "chiron-hei-hk", latinFont: "anton", weight: 900, letterSpacing: 0, note: "粗黑、緊密，像剪貼字" },
    motifs: ["影印海報", "剪貼字", "網點"],
    live: "觀眾會一起喊口號：畫面像影印傳單，粗、快、直接。",
    why: "龐克是 DIY 影印美學：撞色、剪貼字、直接的口號。",
  },
  {
    id: "post-punk",
    label: "後龐克",
    tags: ["post-punk", "coldwave", "darkwave", "gothic rock", "goth rock", "new wave", "no wave"],
    zh: ["後龐克", "冷潮", "新浪潮", "哥德搖滾"],
    palette: { hues: [200, 350], saturation: 0.45, scheme: "complementary", light: "dark", note: "冷峻的黑白，加一個冷色或紅色點綴" },
    scenes: ["grid", "ink", "shards", "gradient"],
    avoid: ["bokeh"],
    lyrics: { verse: "typewriter", chorus: "stack", density: "normal", note: "字像打字機一樣冷冷地出現" },
    motion: "medium",
    typography: { cjkFont: "noto-sans-tc", latinFont: "space-grotesk", weight: 800, letterSpacing: 0.14, note: "寬字距的冷黑體" },
    motifs: ["冷色幾何", "黑白海報"],
    live: "重複的節奏：畫面在重複中慢慢變化，不要花俏。",
    why: "後龐克冷、疏離：黑白幾何加一個冷色點綴。",
  },
  {
    id: "electronic",
    label: "電子",
    tags: ["electronic", "electronica", "edm", "techno", "house", "trance", "synthpop", "synth-pop", "electropop", "dubstep", "drum and bass", "idm", "synthwave", "electro", "future bass"],
    zh: ["電子音樂", "電子樂", "電音", "合成器流行", "電子流行", "電子"],
    palette: { hues: [190, 300, 265], saturation: 1.1, scheme: "complementary", light: "dark", note: "霓虹青、洋紅與紫" },
    scenes: ["grid", "tunnel", "particles", "waves"],
    avoid: ["ink"],
    lyrics: { verse: "hidden", chorus: "impact", density: "sparse", note: "drop 交給畫面，hook 才上巨字" },
    motion: "punchy",
    typography: { cjkFont: "noto-sans-tc", latinFont: "space-grotesk", weight: 800, letterSpacing: 0.08, note: "乾淨的幾何字" },
    motifs: ["光譜音波", "網格地平線", "脈衝光點"],
    live: "drop 是高潮：前面堆疊、drop 一拍切進隧道或網格（LED 安全模式會把閃白改成淡入）。",
    why: "電子樂的畫面就是節拍：霓虹、網格、隧道，跟著 drop 爆開。",
  },
  {
    id: "hip-hop",
    label: "嘻哈",
    tags: ["hip hop", "hip-hop", "rap", "trap", "boom bap", "conscious hip hop", "gangsta rap", "drill", "chinese hip hop", "taiwanese hip hop"],
    zh: ["嘻哈", "饒舌", "說唱", "饒舌歌手"],
    palette: { hues: [45, 275], saturation: 0.95, scheme: "complementary", light: "dark", note: "黑底上的金色與紫" },
    scenes: ["grid", "shards", "motif", "particles"],
    avoid: ["bokeh"],
    lyrics: { verse: "subtitle", chorus: "impact", density: "dense", note: "主歌字很密，讓位給饒舌本身；hook 才上巨字" },
    motion: "punchy",
    typography: { cjkFont: "chiron-hei-hk", latinFont: "bebas-neue", weight: 900, letterSpacing: 0.02, note: "粗黑與窄體大寫" },
    motifs: ["金色字樣", "街頭塗鴉", "影像拼貼"],
    live: "主歌不要逐字動畫；hook 用巨字讓全場一起喊，主唱喊 call 時畫面停一下。",
    why: "嘻哈的字多又快：主歌讓位給饒舌，hook 才上巨字，金色與街頭感。",
  },
  {
    id: "rnb",
    label: "節奏藍調",
    tags: ["r&b", "rnb", "rhythm and blues", "contemporary r&b", "soul", "neo soul", "neo-soul", "funk"],
    zh: ["節奏藍調", "靈魂樂", "放克"],
    palette: { hues: [285, 30], saturation: 0.75, scheme: "split", light: "dark", note: "絲絨般的暖紫與琥珀" },
    scenes: ["bokeh", "gradient", "waves", "nebula"],
    avoid: ["shards"],
    lyrics: { verse: "line-fade", chorus: "karaoke", density: "normal", note: "歌詞跟著 groove 柔柔地出現" },
    motion: "soft",
    typography: { cjkFont: "noto-serif-tc", latinFont: "playfair-display", weight: 700, letterSpacing: 0.04, note: "優雅的襯線" },
    motifs: ["絲絨般的光暈", "夜晚的暖燈"],
    live: "律動慵懶：畫面跟著 groove 呼吸，轉換柔和。",
    why: "R&B 是絲絨與夜晚：暖紫、琥珀、柔焦光斑。",
  },
  {
    id: "jazz",
    label: "爵士",
    tags: ["jazz", "jazz fusion", "smooth jazz", "bossa nova", "swing", "lounge", "jazz pop"],
    zh: ["爵士", "巴薩諾瓦"],
    palette: { hues: [35, 220], saturation: 0.5, scheme: "complementary", light: "dark", note: "煙霧裡的琥珀與深藍" },
    scenes: ["bokeh", "ink", "gradient", "waves"],
    avoid: ["grid", "tunnel"],
    lyrics: { verse: "line-fade", chorus: "stack", density: "normal", note: "歌詞像菜單上的字一樣優雅地出現" },
    motion: "soft",
    typography: { cjkFont: "cactus-classical-serif", latinFont: "playfair-display", weight: 700, letterSpacing: 0.06, note: "舊式明體的復古" },
    motifs: ["煙霧中的舞台燈", "黑膠唱片"],
    live: "即興段落很多：畫面停在同一個氛圍，用手動 cue 跟樂手。",
    why: "爵士是煙霧與夜：琥珀、深藍、舊式襯線字。",
  },
  {
    id: "math-rock",
    label: "數學搖滾",
    tags: ["math rock", "math-rock", "mathrock", "math pop"],
    zh: ["數學搖滾"],
    palette: { hues: [190, 45, 330], saturation: 0.85, scheme: "triadic", light: "mid", note: "乾淨的幾何原色" },
    scenes: ["grid", "shards", "waves", "motif"],
    avoid: ["bokeh", "nebula"],
    lyrics: { verse: "hidden", chorus: "line-fade", density: "sparse", note: "常常是器樂，歌詞只在人聲段出現" },
    motion: "punchy",
    typography: { cjkFont: "noto-sans-tc", latinFont: "space-grotesk", weight: 700, letterSpacing: 0.1, note: "精準的幾何字" },
    motifs: ["精準的幾何格線", "拍點上的色塊"],
    live: "奇數拍與突然的停頓：硬切對準重拍，樂團停的時候畫面也停。",
    why: "數學搖滾靠精準的拍子：乾淨的幾何、色塊，硬切對準停頓。",
  },
  {
    id: "emo",
    label: "情緒搖滾",
    tags: ["emo", "emocore", "midwest emo", "screamo", "emo pop"],
    zh: ["情緒搖滾", "情緒核"],
    palette: { hues: [230, 355], saturation: 0.7, scheme: "complementary", light: "dark", note: "瘀青般的冷藍與暗紅" },
    scenes: ["rain", "ink", "particles", "shards"],
    avoid: ["bokeh"],
    lyrics: { verse: "line-fade", chorus: "karaoke", density: "normal", note: "副歌全場一起嘶吼：歌詞要大、要準時" },
    motion: "medium",
    typography: { cjkFont: "noto-sans-tc", latinFont: "bebas-neue", weight: 800, letterSpacing: 0.04, note: "粗黑的直接" },
    motifs: ["手寫的歌詞本", "雨夜的車窗"],
    live: "觀眾會一起唱副歌：歌詞提前出現，主唱把麥克風交給觀眾時保持在畫面上。",
    why: "情緒搖滾是青春的傷口：冷藍、暗紅、雨，副歌全場一起唱。",
  },
  {
    id: "psychedelic",
    label: "迷幻",
    tags: ["psychedelic", "psychedelic rock", "psychedelia", "neo-psychedelia", "space rock", "krautrock", "psychedelic pop", "stoner rock"],
    zh: ["迷幻", "迷幻搖滾", "太空搖滾"],
    palette: { hues: [290, 30, 160], saturation: 1.05, scheme: "triadic", light: "mid", note: "高彩度的紫、橘與綠的漩渦" },
    scenes: ["ink", "nebula", "tunnel", "waves"],
    avoid: ["grid"],
    lyrics: { verse: "subtitle", chorus: "line-fade", density: "sparse", note: "長段即興，不必跟每一句歌詞" },
    motion: "soft",
    typography: { cjkFont: "iansui", latinFont: "playfair-display", weight: 700, letterSpacing: 0.06, note: "手寫感的字，像迷幻海報" },
    motifs: ["流動的色彩漩渦", "萬花筒"],
    live: "即興會延長：讓畫面持續流動變形，用手動 cue 對準回到主旋律的時刻。",
    why: "迷幻樂的畫面會流動變形：高彩度的漩渦與墨流。",
  },
  {
    id: "alt-rock",
    label: "搖滾",
    tags: ["alternative rock", "alternative", "alt rock", "grunge", "britpop", "rock", "pop rock", "hard rock", "progressive rock", "art rock", "rock and roll"],
    zh: ["另類搖滾", "流行搖滾", "硬式搖滾", "英倫搖滾", "搖滾"],
    palette: { hues: [30, 210], saturation: 0.8, scheme: "split", light: "mid", note: "舞台燈的琥珀與鋼藍" },
    scenes: ["particles", "shards", "grid", "ink"],
    avoid: [],
    lyrics: { verse: "line-fade", chorus: "karaoke", density: "normal", note: "主歌收、副歌放，觀眾跟唱" },
    motion: "medium",
    typography: { cjkFont: "chiron-hei-hk", latinFont: "bebas-neue", weight: 800, letterSpacing: 0.04, note: "有力量的粗黑體" },
    motifs: ["舞台燈束", "粗顆粒的現場感"],
    live: "典型的搖滾結構：最後一次副歌最炸，尾奏收在一道光。",
    why: "搖滾的畫面像舞台燈本身：琥珀與鋼藍，副歌一次比一次亮。",
  },
  {
    id: "ambient",
    label: "氛圍",
    tags: ["ambient", "drone", "new age", "dark ambient", "ambient pop", "downtempo", "chillout", "lo-fi", "lofi", "chillwave"],
    zh: ["氛圍音樂", "環境音樂", "低傳真"],
    palette: { hues: [200, 260], saturation: 0.4, scheme: "analogous", light: "dark", note: "低彩度的藍灰色場" },
    scenes: ["gradient", "nebula", "waves", "bokeh"],
    avoid: ["shards", "tunnel", "grid"],
    lyrics: { verse: "hidden", chorus: "line-fade", density: "sparse", note: "幾乎不放歌詞，偶爾一句淡入" },
    motion: "soft",
    typography: { cjkFont: "noto-serif-tc", latinFont: "space-grotesk", weight: 600, letterSpacing: 0.14, note: "輕、寬的字距" },
    motifs: ["緩慢漂移的色場", "呼吸般的光"],
    live: "幾乎沒有段落感：畫面慢慢漂移，避免任何突兀的變化。",
    why: "氛圍音樂不推進，畫面就不要推進：低彩度的色場慢慢漂移。",
  },
  {
    id: "pop",
    label: "流行",
    tags: ["pop", "mandopop", "c-pop", "cantopop", "j-pop", "k-pop", "dance-pop", "dance pop", "ballad", "taiwanese pop", "chinese pop"],
    zh: ["華語流行", "國語流行", "流行音樂", "流行歌手", "抒情", "情歌", "偶像團體", "流行"],
    palette: { hues: [330, 200], saturation: 0.85, scheme: "split", light: "mid", note: "乾淨明亮的粉與藍" },
    scenes: ["particles", "bokeh", "gradient", "shards"],
    avoid: [],
    lyrics: { verse: "line-fade", chorus: "karaoke", density: "normal", note: "觀眾熟悉歌詞：副歌整行出現讓全場跟唱" },
    motion: "medium",
    typography: { cjkFont: "noto-sans-tc", latinFont: "space-grotesk", weight: 700, letterSpacing: 0.04, note: "最好讀的黑體" },
    motifs: ["柔光粒子", "明亮的色塊"],
    live: "副歌整行提前出現；主唱把麥克風交給觀眾時保持歌詞在畫面上。",
    why: "流行歌的觀眾會跟唱：乾淨、明亮，歌詞清楚好讀。",
  },
];

/** General tags say little on their own: they only decide when nothing more specific matched. */
export const GENERAL_TAGS: ReadonlySet<string> = new Set(["rock", "pop", "indie", "alternative", "electronic", "folk", "metal", "punk", "jazz", "流行", "搖滾", "電子"]);
